---
- name: create nginx script for app
  template:
    src: "app.conf.j2"
    dest: "/etc/nginx/sites-available/{{item.name}}.conf"
  become: yes

- name: link script
  file:
    src: "/etc/nginx/sites-available/{{item.name}}.conf"
    dest: "/etc/nginx/sites-enabled/{{item.name}}.conf"
    state: link
  become: yes
