- include_tasks: 'nginx.yml'
  when: nginx != false

- include_tasks: 'ssl.yml'

- name: restart nginx
  service: name=nginx state=restarted enabled=true
  become: true
  when: nginx != false

- name: apps
  include_tasks: "app.yml"
  with_items: "{{apps}}"
