- name: install nginx
  include: 'nginx.yml'
  become: yes
  when: nginx != false

- name: ssl
  include: 'ssl.yml'
  become: yes

- name: default
  template:
    src: "default.conf.j2"
    dest: "{{nginx_path}}/sites-enabled/default.conf"
  vars:
    ssl_name: "{{ ssl[0]['name'] }}"

- name: restart nginx
  service: name=nginx state=restarted enabled=true
  become: true
  when: nginx != false

- name: apps
  include: "app.yml"
  become: yes
  with_items: "{{apps}}"

