- name: create ssl path
  file:
    path: "{{nginx_path}}/ssl"
    state: directory
    mode: 0700

- name: create sub ssl path
  file:
    path: "{{nginx_path}}/ssl/{{ item['name'] }}"
    state: directory
    mode: 0700
  with_items: "{{ ssl }}"

- name: copy files
  copy:
    src: "{{ item[0][ item[1] ] }}"
    dest: "{{nginx_path}}/ssl/{{ item[0]['name'] }}/{{ item[0][ item[1] ] | basename}}"
  with_nested:
    - "{{ ssl }}"
    - ['crt', 'key', 'dhparam']

- name: copy config
  template:
    src: "ssl.conf.j2"
    dest: "{{nginx_path}}/ssl/ssl_{{ item['name'] }}.conf"
  with_items: "{{ ssl }}"
